### ISSUE TITLE
Running withour wind speed or direction

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Dynamic-Fire-System#1]
If you run Dynamic Fire and you don't supply wind speed/ wind direction, then the extension should trigger an error.  Right now it runs but produces no fire.

**Comment by akretchun** [comment]
Noted. I will try and get to it by next week. Thanks!

```
-Alec
```

On Tue, Oct 27, 2015 at 7:47 AM, Robert Scheller notifications@github.com
wrote:

> Assigned #1
> https://github.com/LANDIS-II-Foundation/Extension-Dynamic-Fire/issues/1
> to @akretchun https://github.com/akretchun.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LANDIS-II-Foundation/Extension-Dynamic-Fire/issues/1#event-446862176
> .

## 

Alec Kretchun

**Comment by rmscheller** [comment]
Needs testing.

**Comment by bmarron18** [comment]
QAQC passed; close issue

[PWL82_QAQC_DynamicFire_20170928 .txt](https://github.com/LANDIS-II-Foundation/Extension-Dynamic-Fire-System/files/1341324/PWL82_QAQC_DynamicFire_20170928.txt)
